{
	"dataGameSynthesize1":[{
		"id":"game_3",
		"time":"",
    "thumbUrl":"https://leach-chen.github.io/storeh5game1/3/h5game1_3_t.jpg",
    "previewUrl":"https://leach-chen.github.io/storeh5game1/3/h5game1_3_p/",
    "downloadUrl":"https://leach-chen.github.io/storeh5game1/3/h5game1_3_d.zip",
		"title":"H5酷跑游戏",
    "description":"跑酷游戏，即刻挑战",
    "type":"game_synthesize_1",
    "author":"zzfriend",
    "authorurl":"http://bbs.zzfriend.com/",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
		"tag": "game",
    "sold":true
  },
		{
			"id":"game_1",
			"time":"",
			"thumbUrl": "https://leach-chen.github.io/storeh5game1/1/h5game1_1_t.jpg",
			"previewUrl": "https://leach-chen.github.io/storeh5game1/1/h5game1_1_p_flappy/",
			"downloadUrl": "https://leach-chen.github.io/storeh5game1/1/h5game1_1_d_flappy.zip",
			"originalUrl": "",
			"title":"H5 Flappy Bird游戏",
			"description": "Flappy Bird 试试能得多少分",
			"type": "game_synthesize_1",
			"author": "html5tricks",
			"authorurl": "https://www.html5tricks.com/",
			"gitauthor": "",
			"gitrepo": "",
			"byauthor": "",
			"byauthorurl": "",
			"tag": "game",
			"sold": true
		},
		{
			"id":"game_2",
			"time":"",
			"thumbUrl": "https://leach-chen.github.io/storeh5game1/2/h5game1_2_t.jpg",
			"previewUrl": "https://leach-chen.github.io/storeh5game1/2/h5game1_2_p_fruit/",
			"downloadUrl": "https://leach-chen.github.io/storeh5game1/2/h5game1_2_d_fruit.zip",
			"originalUrl": "https://www.html5tricks.com/html5-fruit-ninja.html",
			"title":"H5切水果游戏",
			"description": "经典切水果游戏",
			"type": "game_synthesize_1",
			"author": "html5tricks",
			"authorurl": "https://www.html5tricks.com/",
			"gitauthor": "",
			"gitrepo": "",
			"byauthor": "",
			"byauthorurl": "",
			"tag": "game",
			"sold": true
		}
	],
	"dataGameChesscard1":[{
    "id":"game_5",
    "thumbUrl":"https://leach-chen.github.io/storeh5game1/5/h5game1_5_t.jpg",
    "previewUrl":"https://leach-chen.github.io/storeh5game1/5/h5game1_5_p/",
    "downloadUrl":"https://leach-chen.github.io/storeh5game1/5/h5game1_5_d.rar",
		"title":"H5象棋对战游戏",
    "description":"象棋对战游戏，可设置难度",
    "type":"game_chesscard_1",
    "author":"html5tricks",
    "authorurl":"https://www.html5tricks.com",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"game|棋牌",
  "time":"20190319103534"
  },{
    "id":"game_4",
    "thumbUrl":"https://leach-chen.github.io/storeh5game1/4/h5game1_4_t.jpg",
    "previewUrl":"https://leach-chen.github.io/storeh5game1/4/h5game1_4_p/",
    "downloadUrl":"https://leach-chen.github.io/storeh5game1/4/h5game1_4_d.rar",
		"title":"H5五子棋对战游戏",
    "description":"五子棋游戏，可设置对战难度",
    "type":"game_chesscard_1",
    "author":"html5tricks",
    "authorurl":"https://www.html5tricks.com",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"game|棋牌",
  "time":"20190319102302"
  }
	],
	"dataGameRisk1":[
	],
	"dataGameSmart1":[{
    "id":"game_7",
    "thumbUrl":"https://leach-chen.github.io/storeh5game1/7/h5game1_7_t.jpg",
    "previewUrl":"https://leach-chen.github.io/storeh5game1/7/h5game1_7_p/",
    "downloadUrl":"https://codeload.github.com/gd4Ark/linkup/zip/master",
		"title":"H5连连看游戏",
    "description":"连连看游戏",
    "type":"game_smart_1",
    "author":"",
    "authorurl":"https://github.com/gd4Ark",
    "gitauthor":"gd4Ark",
    "gitrepo":"linkup",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"game",
  "time":"20190328165747"
  }
	],
	"dataGameShoot1":[{
    "id":"game_6",
    "thumbUrl":"https://leach-chen.github.io/storeh5game1/6/h5game1_6_t.jpg",
    "previewUrl":"https://leach-chen.github.io/storeh5game1/6/h5game1_6_p/",
    "downloadUrl":"https://codeload.github.com/gd4Ark/star-battle/zip/master",
		"title":"H5星际对战游戏",
    "description":"星际大战,使用原生JavaScript ES6 + Canvas 开发的一个类似雷电战机的 HTML5 游戏",
    "type":"game_shoot_1",
    "author":"",
    "authorurl":"https://github.com/gd4Ark",
    "gitauthor":"gd4Ark",
    "gitrepo":"star-battle",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"game",
  "time":"20190328164943"
  }
	]
}
