{
	"dataGameSynthesize1":[{
		"id":"game_3",
		"time":"",
    "thumbUrl":"https://www.leachchen.com/storeh5game1/3/h5game1_3_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeh5game1/3/h5game1_3_p/",
    "downloadUrl":"https://www.leachchen.com/storeh5game1/3/h5game1_3_d.zip",
    "description":"跑酷游戏，即刻挑战",
    "type":"game_synthesize_1",
    "author":"zzfriend",
    "authorurl":"http://bbs.zzfriend.com/",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
		"tag": "game",
    "sold":true
  },
		{
			"id":"game_1",
			"time":"",
			"thumbUrl": "https://www.leachchen.com/storeh5game1/1/h5game1_1_t.jpg",
			"previewUrl": "https://www.leachchen.com/storeh5game1/1/h5game1_1_p_flappy/",
			"downloadUrl": "https://www.leachchen.com/storeh5game1/1/h5game1_1_d_flappy.zip",
			"originalUrl": "",
			"description": "Flappy Bird 试试能得多少分",
			"type": "game_synthesize_1",
			"author": "html5tricks",
			"authorurl": "https://www.html5tricks.com/",
			"gitauthor": "",
			"gitrepo": "",
			"byauthor": "",
			"byauthorurl": "",
			"tag": "game",
			"sold": true
		},
		{
			"id":"game_2",
			"time":"",
			"thumbUrl": "https://www.leachchen.com/storeh5game1/2/h5game1_2_t.jpg",
			"previewUrl": "https://www.leachchen.com/storeh5game1/2/h5game1_2_p_fruit/",
			"downloadUrl": "https://www.leachchen.com/storeh5game1/2/h5game1_2_d_fruit.zip",
			"originalUrl": "https://www.html5tricks.com/html5-fruit-ninja.html",
			"description": "经典切水果游戏",
			"type": "game_synthesize_1",
			"author": "html5tricks",
			"authorurl": "https://www.html5tricks.com/",
			"gitauthor": "",
			"gitrepo": "",
			"byauthor": "",
			"byauthorurl": "",
			"tag": "game",
			"sold": true
		}
	],
	"dataGameChesscard1":[{
    "id":"game_5",
    "thumbUrl":"https://www.leachchen.com/storeh5game1/5/h5game1_5_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeh5game1/5/h5game1_5_p/",
    "downloadUrl":"https://www.leachchen.com/storeh5game1/5/h5game1_5_d.rar",
    "description":"象棋对战游戏，可设置难度",
    "type":"game_chesscard_1",
    "author":"html5tricks",
    "authorurl":"https://www.html5tricks.com",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"game|棋牌",
  "time":"20190319103534"
  },{
    "id":"",
    "thumbUrl":"https://www.leachchen.com/storeh5game1/4/h5game1_4_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeh5game1/4/h5game1_4_p/",
    "downloadUrl":"https://www.leachchen.com/storeh5game1/4/h5game1_4_d.rar",
    "description":"五子棋游戏，可设置对战难度",
    "type":"game_chesscard_1",
    "author":"html5tricks",
    "authorurl":"https://www.html5tricks.com",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"game|棋牌",
  "time":"20190319102302"
  }
	],
	"dataGameRisk1":[
	],
	"dataGameSmart1":[
	],
	"dataGameShoot1":[
	]
}
