{
	  "dataAndroidFull1":[
		{
			"id":"android_1",
			"time":"",
			"thumbUrl": "https://www.leachchen.com/storeandroid1/1/android1_1_t.png",
			"previewUrl": "https://www.leachchen.com/storeandroid1/1/android1_1_p.png",
			"downloadUrl": "https://codeload.github.com/harjot-oberai/MusicDNA/zip/master",
			"description": "一款舒适的音乐播放器",
			"type": "android_full_1",
			"author": "",
			"authorurl": "https://github.com/harjot-oberai",
			"gitauthor": "harjot-oberai",
			"gitrepo": "MusicDNA",
			"byauthor": "",
			"byauthorurl": "",
			"tag": "android|animation",
			"sold": true
		}
	],
	"dataAndroidAnimation1":[{
    "id":"android_6",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/6/android1_6_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/6/android1_6_p.gif",
    "downloadUrl":"https://codeload.github.com/xh2009cn/GalleryAnimations/zip/master",
    "description":"炫酷的相册动画合集，集合了粒子、雪花、气泡、蝴蝶心形路径、星星、相册翻页等效果",
    "type":"android_animation_1",
    "author":"",
    "authorurl":"https://github.com/xh2009cn",
    "gitauthor":"xh2009cn",
    "gitrepo":"GalleryAnimations",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190315114755"
  },
		{
			 "id":"android_2",
		   "time":"",
			 "thumbUrl":"https://www.leachchen.com/storeandroid1/2/android1_2_t.jpg",
			 "previewUrl":"https://www.leachchen.com/storeandroid1/2/android1_2_p.gif",
			 "downloadUrl": "https://codeload.github.com/Airbnb/lottie-android/zip/master",
			 "description":"airbnb的lottie酷炫动画库",
			 "type":"android_animation_1",
			 "author":"",
			 "authorurl":"https://github.com/airbnb",
			 "gitauthor":"Airbnb",
			 "gitrepo":"lottie-android",
			 "byauthor":"",
			 "byauthorurl":"",
			 "tag": "android",
			 "sold":true
		  }
	],
	"dataAndroidView1":[{
    "id":"android_7",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/7/android1_7_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/7/android1_7_p.gif",
    "downloadUrl":"https://codeload.github.com/LichFaker/ScaleView/zip/master",
    "description":"自定义view实现的滚动刻度尺,可水平和竖直方向",
    "type":"android_view_1",
    "author":"",
    "authorurl":"https://github.com/LichFaker",
    "gitauthor":"LichFaker",
    "gitrepo":"ScaleView",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android|自定义View",
  "time":"20190317233903"
  },{
		"id":"android_5",
		"time":"",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/5/android1_5_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/5/android1_5_p.gif",
    "downloadUrl":"https://codeload.github.com/Ajian-studio/GADownloading/zip/master",
    "description":"一款绚丽的LoadingView，有多种效果",
    "type":"android_view_1",
    "author":"",
    "authorurl":"https://github.com/Ajian-studio",
    "gitauthor":"Ajian-studio",
    "gitrepo":"GADownloading",
    "byauthor":"",
    "byauthorurl":"",
  	"tag": "android",
    "sold":true
  },
		{
			"id":"android_3",
			"time":"",
			"thumbUrl":"https://www.leachchen.com/storeandroid1/3/android1_3_t.png",
			"previewUrl":"https://www.leachchen.com/storeandroid1/3/android1_3_p.gif",
			"downloadUrl":"https://codeload.github.com/woxingxiao/BubbleSeekBar/zip/master",
			"description":"自定义SeekBar，进度变化更以可视化气泡样式呈现",
			"type":"android_view_1",
			"author":"",
			"authorurl":"https://github.com/woxingxiao",
			"gitauthor":"woxingxiao",
			"gitrepo":"BubbleSeekBar",
			"byauthor":"",
			"byauthorurl":"",
			"tag": "android",
			"sold":true
		  }
	],

	"dataAndroidSynthesize1":[{
    "id":"android_9",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/9/android1_9_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/9/android1_9_p.gif",
    "downloadUrl":"https://codeload.github.com/didi/DoraemonKit/zip/master",
    "description":"一款辅助开发的工具�",
    "type":"android_synthesize_1",
    "author":"",
    "authorurl":"https://github.com/didi",
    "gitauthor":"didi",
    "gitrepo":"DoraemonKit",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190318175717"
  },{
		"id":"android_4",
		"time":"",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/4/android1_4_t.png",
    "previewUrl":"https://blankj.com/2016/07/31/android-utils-code/",
    "downloadUrl":"https://codeload.github.com/Blankj/AndroidUtilCode/zip/master",
    "description":"工具类大全应有尽有，更多请点击预览查看",
    "type":"android_synthesize_1",
    "author":"",
    "authorurl":"https://blankj.com/",
    "gitauthor":"Blankj",
    "gitrepo":"AndroidUtilCode",
    "byauthor":"",
    "byauthorurl":"",
  	"tag": "android",
    "sold":true
  }],
	"dataAndroidArchitecture1":[
	],
	"dataAndroidComponent1":[{
    "id":"android_8",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/8/android1_8_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeandroid1/8/android1_8_p.gif",
    "downloadUrl":"https://codeload.github.com/scwang90/SmartRefreshLayout/zip/master",
    "description":"下拉刷新、上拉加载、二级刷新、淘宝二楼、RefreshLayout、OverScroll，Android智能下拉刷新框架，支持越界回弹、越界拖动，具有极强的扩展性，集成了几十种炫酷的Header和 Footer",
    "type":"android_component_1",
    "author":"",
    "authorurl":"https://github.com/scwang90",
    "gitauthor":"scwang90",
    "gitrepo":"SmartRefreshLayout",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android|component",
  "time":"20190318155851"
  }
	]


}
