{
	  "dataAndroidFull1":[
		{
			"id":"android_1",
			"time":"",
			"thumbUrl": "https://www.leachchen.com/storeandroid1/1/android1_1_t.png",
			"previewUrl": "https://www.leachchen.com/storeandroid1/1/android1_1_p.png",
			"downloadUrl": "https://codeload.github.com/harjot-oberai/MusicDNA/zip/master",
			"title":"Android音乐播放器",
			"description": "一款舒适的音乐播放器",
			"type": "android_full_1",
			"author": "",
			"authorurl": "https://github.com/harjot-oberai",
			"gitauthor": "harjot-oberai",
			"gitrepo": "MusicDNA",
			"byauthor": "",
			"byauthorurl": "",
			"tag": "android|animation",
			"sold": true
		}
	],
	"dataAndroidAnimation1":[{
    "id":"android_6",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/6/android1_6_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/6/android1_6_p.gif",
    "downloadUrl":"https://codeload.github.com/xh2009cn/GalleryAnimations/zip/master",
		"title":"Android酷炫粒子动画合集",
    "description":"炫酷的相册动画合集，集合了粒子、雪花、气泡、蝴蝶心形路径、星星、相册翻页等效果",
    "type":"android_animation_1",
    "author":"",
    "authorurl":"https://github.com/xh2009cn",
    "gitauthor":"xh2009cn",
    "gitrepo":"GalleryAnimations",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190315114755"
  },
		{
			 "id":"android_2",
		   "time":"",
			 "thumbUrl":"https://www.leachchen.com/storeandroid1/2/android1_2_t.jpg",
			 "previewUrl":"https://www.leachchen.com/storeandroid1/2/android1_2_p.gif",
			 "downloadUrl": "https://codeload.github.com/Airbnb/lottie-android/zip/master",
			 "title":"Android lottie 动画",
			 "description":"airbnb的lottie酷炫动画库",
			 "type":"android_animation_1",
			 "author":"",
			 "authorurl":"https://github.com/airbnb",
			 "gitauthor":"Airbnb",
			 "gitrepo":"lottie-android",
			 "byauthor":"",
			 "byauthorurl":"",
			 "tag": "android",
			 "sold":true
		  }
	],
	"dataAndroidView1":[{
    "id":"android_12",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/12/android1_12_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/12/android1_12_p.gif",
    "downloadUrl":"https://codeload.github.com/frakbot/CreditsRoll/zip/master",
		"title":"Android自定义view 星球大战字幕",
    "description":"实现星球大战字幕效果",
    "type":"android_view_1",
    "author":"",
    "authorurl":"https://github.com/frakbot",
    "gitauthor":"frakbot",
    "gitrepo":"CreditsRoll",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190330232400"
  },{
    "id":"android_11",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/11/android1_11_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeandroid1/11/android1_11_p.gif",
    "downloadUrl":"https://codeload.github.com/zcweng/SwitchButton/zip/master",
		"title":"Android自定义view SwitchButton",
    "description":"自定义view实现的SwitchButton多种样式",
    "type":"android_view_1",
    "author":"",
    "authorurl":"https://github.com/zcweng",
    "gitauthor":"zcweng",
    "gitrepo":"SwitchButton",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190330231943"
  },{
    "id":"android_10",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/10/android1_10_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/10/android1_10_p.gif",
    "downloadUrl":"https://www.leachchen.com/storeandroid1/10/android1_10_d.zip",
		"title":"Android自定义view flappybird游戏",
    "description":"kotlin语言写的android flappybird游戏，整个视图是一个自定义view。",
    "type":"android_view_1",
    "author":"apkbus",
    "authorurl":"http://www.apkbus.com",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android|自定义view|game",
  "time":"20190328000553"
  },{
    "id":"android_7",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/7/android1_7_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/7/android1_7_p.gif",
    "downloadUrl":"https://codeload.github.com/LichFaker/ScaleView/zip/master",
		"title":"Android自定义view 刻度尺",
    "description":"自定义view实现的滚动刻度尺,可水平和竖直方向",
    "type":"android_view_1",
    "author":"",
    "authorurl":"https://github.com/LichFaker",
    "gitauthor":"LichFaker",
    "gitrepo":"ScaleView",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android|自定义View",
  "time":"20190317233903"
  },{
		"id":"android_5",
		"time":"",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/5/android1_5_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/5/android1_5_p.gif",
    "downloadUrl":"https://codeload.github.com/Ajian-studio/GADownloading/zip/master",
		"title":"Android自定义view LoadingView",
    "description":"一款绚丽的LoadingView，有多种效果",
    "type":"android_view_1",
    "author":"",
    "authorurl":"https://github.com/Ajian-studio",
    "gitauthor":"Ajian-studio",
    "gitrepo":"GADownloading",
    "byauthor":"",
    "byauthorurl":"",
  	"tag": "android",
    "sold":true
  },
		{
			"id":"android_3",
			"time":"",
			"thumbUrl":"https://www.leachchen.com/storeandroid1/3/android1_3_t.png",
			"previewUrl":"https://www.leachchen.com/storeandroid1/3/android1_3_p.gif",
			"downloadUrl":"https://codeload.github.com/woxingxiao/BubbleSeekBar/zip/master",
			"title":"Android自定义view SeekBar",
			"description":"自定义SeekBar，进度变化更以可视化气泡样式呈现",
			"type":"android_view_1",
			"author":"",
			"authorurl":"https://github.com/woxingxiao",
			"gitauthor":"woxingxiao",
			"gitrepo":"BubbleSeekBar",
			"byauthor":"",
			"byauthorurl":"",
			"tag": "android",
			"sold":true
		  }
	],

	"dataAndroidSynthesize1":[{
    "id":"android_9",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/9/android1_9_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/9/android1_9_p.gif",
    "downloadUrl":"https://codeload.github.com/didi/DoraemonKit/zip/master",
		"title":"Android 开发辅助工具",
    "description":"一款辅助开发的工具,能够监测卡顿，CPU性能，沙盒目录查看等功能，添加依赖后APP里便会有入口进入各项功能选择界面。APP记得打开悬浮窗权限",
    "type":"android_synthesize_1",
    "author":"",
    "authorurl":"https://github.com/didi",
    "gitauthor":"didi",
    "gitrepo":"DoraemonKit",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190318175717"
  },{
		"id":"android_4",
		"time":"",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/4/android1_4_t.png",
    "previewUrl":"https://blankj.com/2016/07/31/android-utils-code/",
    "downloadUrl":"https://codeload.github.com/Blankj/AndroidUtilCode/zip/master",
		"title":"Android 工具类",
    "description":"工具类大全应有尽有，更多请点击预览查看",
    "type":"android_synthesize_1",
    "author":"",
    "authorurl":"https://blankj.com/",
    "gitauthor":"Blankj",
    "gitrepo":"AndroidUtilCode",
    "byauthor":"",
    "byauthorurl":"",
  	"tag": "android",
    "sold":true
  }],
	"dataAndroidArchitecture1":[
	],
	"dataAndroidComponent1":[{
    "id":"android_14",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/14/android1_14_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeandroid1/14/android1_14_p.png",
    "downloadUrl":"https://codeload.github.com/xuexiangjys/XUI/zip/master",
    "title":"一个简洁而优雅的Android原生UI框架，解放你的双手",
    "description":"一个简洁而又优雅的Android原生UI框架，解放你的双手。简洁优雅，尽可能少得引用资源文件的数量，项目库整体大小不足1M(打包后大约644k）。组件丰富，提供了绝大多数我们在开发者常用的功能组件。使用简单，为方便快速开发，提高开发效率，对api进行了优化，提供一键式接入。样式统一，框架提供了一系列统一的样式，使UI整体看上去美观和谐。兼容性高，框架还提供了3种不同尺寸设备的样式（4.5英寸、7英寸和10英寸），并且最低兼容到Android 17, 让UI兼容性更强。扩展性强，各组件提供了丰富的属性和样式API，可以通过设置不同的样式属性，构建不同风格的UI。",
    "type":"android_component_1",
    "author":"",
    "authorurl":"https://github.com/xuexiangjys",
    "gitauthor":"xuexiangjys",
    "gitrepo":"XUI",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190425151741"
  },{
    "id":"android_13",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/13/android1_13_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/13/android1_13_p.gif",
    "downloadUrl":"https://codeload.github.com/xuexiangjys/XAOP/zip/master",
    "title":"一个轻量级的AOP(Android)应用框架",
    "description":"一个轻量级的AOP(Android)应用框架。囊括了最实用的AOP应用。支持快速点击切片、支持动态申请权限切片、支持主线程切片、支持IO线程切片、支持日志打印切片...,具体，具体可点击start，前往项目主页查看具体介绍",
    "type":"android_component_1",
    "author":"",
    "authorurl":"https://github.com/xuexiangjys",
    "gitauthor":"xuexiangjys",
    "gitrepo":"XAOP",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190425134022"
  },{
    "id":"android_8",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/8/android1_8_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeandroid1/8/android1_8_p.gif",
    "downloadUrl":"https://codeload.github.com/scwang90/SmartRefreshLayout/zip/master",
		"title":"Android 上拉下拉刷新控件",
    "description":"下拉刷新、上拉加载、二级刷新、淘宝二楼、RefreshLayout、OverScroll，Android智能下拉刷新框架，支持越界回弹、越界拖动，具有极强的扩展性，集成了几十种炫酷的Header和 Footer",
    "type":"android_component_1",
    "author":"",
    "authorurl":"https://github.com/scwang90",
    "gitauthor":"scwang90",
    "gitrepo":"SmartRefreshLayout",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android|component",
  "time":"20190318155851"
  }
],

"dataAndroidMedia1":[{
    "id":"android_16",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/16/android1_16_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/16/android1_16_p.png",
    "downloadUrl":"https://codeload.github.com/LanSoSdk/LanSoEditor_common/zip/master",
    "title":"可能是android系统中对ffmpeg封装最好的免费SDK",
    "description":"在android系统封装好的ffmpeg. 免费. 采用硬件加速,更快的视频转码.裁剪,剪切,分离,合并,转换,拼接,水印,叠加,混合,转码,压缩, 变速，添加LOGO，添加滤镜，添加背景音乐，加速减速视频，倒放音视频, 多个视频合成等工作; 和普通的ffmpeg相比, 更快速。<br><br><strong>主要特点:</strong><br>增加 H264硬件编码器 和 H264硬件解码器, 处理速度极大提升;<br>增加40多个常见方法,编写各种辅助处理类.<br>SDK已运行二年左右,商用APP200+.<br><br><strong>免费策略:</strong><br>此SDK已运行二年左右,商用APP200+, 现在免费.<br>H264硬件解码器免费，硬件加速编码器不免费; 免费版本自动切换到libx264编码<br>SDK不访问网络,完全本地处理.<br>个人和公司都可以商用,不需要和我们说明.<br>随我们专业版定期升级,维护.<br>遇到问题在issue中解答;<br>我们提供有偿技术支持和定制服务,详情见下面.",
    "type":"android_media_1",
    "author":"",
    "authorurl":"https://github.com/LanSoSdk",
    "gitauthor":"LanSoSdk",
    "gitrepo":"LanSoEditor_common",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190425162625"
  },{
    "id":"android_15",
    "thumbUrl":"https://www.leachchen.com/storeandroid1/15/android1_15_t.png",
    "previewUrl":"https://www.leachchen.com/storeandroid1/15/android1_15_p.gif",
    "downloadUrl":"https://codeload.github.com/yangchaojiang/yjPlay/zip/master",
    "title":"基于exoPlayer 自定义播放器 JPlayer",
    "description":"一个支持自定义UI布局,流式API, 加密,直播 ,亮度,音量,快进等手势 ,广告视频预览,多种加载模式 ,多种分辨率切换 ,多种封面图, 自定义数据源,列表播放,倍数播放,边播变缓存不是使用AndroidVideoCache</font>,离线播放,神奇的播放器。<br><br>exoPlayer自定义播放器JPlayer支持功能：<br>ExoUserPlayer 基本播放（默认关闭手势 亮度，音量，快进，等手势，支持自定义布局）<br>自动适配适配TV。<br>支持横屏和竖屏两种模式全屏。<br>适配音频控制布局。<br>支持广告视频预览(轻松实现，完美切换，可自定义)。<br>支持多种分辨率视频切换。<br>缓存下载加密视频功能（边播变缓存轻松实现不是使用AndroidVideoCache。<br>支持自定义多种 kttp,Rtmp,Https,Cronet等协议。<br>支持列表集合 播放视频（列表到详情播放完美过度）<br>支持多种文件类型，MP4，M4A，WebM，Matroska,Ogg,WAV，MP3，MPEG-TS，MPEG-PS，FLV，ADTS (AAC)，Flac，M3U8,mkv 等。<br>支持网络类型 提示是否播放(可自定义屏蔽)。<br>支持视频加载布局, 错误布局,重播布局，提示布局自定义，更灵活实现自己布局样式。<br>支持视频加速慢速播放。<br>支持多种视频封面图（两种模式封面图）。<br>支持支持自定义MediaSource。<br>支持精简版和完整版，选择使用更丰富。<br>增加离线下载辅助类ExoWholeDownLoadManger,ExoWholeDownloadTracker,ExoDownLoadManger,DownloadService()-->戳我)<br>支持播放锁屏功能和控制布局显示显示动画效果.<br>支持返回按钮和全屏按钮图标自定义。<br>支持自定义视频封面布局.(视频封面图布局样式完美多样化)。<br>支持视频实时进度（头条底部进度）。<br>支持流式API方式调用。<br>",
    "type":"android_media_1",
    "author":"",
    "authorurl":"https://github.com/yangchaojiang",
    "gitauthor":"yangchaojiang",
    "gitrepo":"yjPlay",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"android",
  "time":"20190425160239"
  }
]


}
