{
	"dataFlutterFull1":[{
    "id":"flutter_3",
    "thumbUrl":"https://www.leachchen.com/storeflutter1/5/flutter1_3_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeflutter1/5/flutter1_3_p.jpg",
    "downloadUrl":"https://codeload.github.com/StrongX/readBook/zip/master",
    "title":"flutter小说app",
    "description":"一个小说app，用flutter实现，资源全部在线从起点和第三方网站爬取",
    "type":"flutter_full_1",
    "author":"",
    "authorurl":"https://github.com/StrongX",
    "gitauthor":"StrongX",
    "gitrepo":"readBook",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"flutter",
  "time":"20190430171807"
  },{
    "id":"flutter_2",
    "thumbUrl":"https://www.leachchen.com/storeflutter1/2/flutter1_2_t.jpg",
    "previewUrl":"https://www.leachchen.com/storeflutter1/2/flutter1_2_p.jpg",
    "downloadUrl":"https://codeload.github.com/MeandNi/Flutter_ZhiHu/zip/master",
		"title":"Flutter仿知乎App",
    "description":"开发知乎App的Flutter版。技术栈：flutter+redux+sqflite。",
    "type":"flutter_full_1",
    "author":"",
    "authorurl":"https://github.com/MeandNi",
    "gitauthor":"MeandNi",
    "gitrepo":"Flutter_ZhiHu",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true,
    "tag":"flutter",
  "time":"20190330225248"
  },{
		  "id":"flutter_1",
		  "time":"",
			"thumbUrl":"https://www.leachchen.com/storeflutter1/1/flutter1_1_t.jpg",
			"previewUrl":"https://www.leachchen.com/storeflutter1/1/flutter1_1_p.gif",
			"downloadUrl": "https://codeload.github.com/alibaba/flutter-go/zip/master",
			"title":"Flutter阿里学习项目",
			"description":"阿里Flutter学习项目，组件丰富",
			"type":"flutter_full_1",
			"author":"",
			"authorurl":"https://github.com/alibaba/",
			"gitauthor":"alibaba",
			"gitrepo":"flutter-go",
			"byauthor":"",
			"byauthorurl":"",
			"tag": "flutter",
			"sold":true


		}
	],
		"dataFlutterView1":[],
		"dataFlutterSynthesize1":[],
}
