{
	"dataToolSynthesize1":[{
    "thumbUrl":"https://www.leachchen.com/storetool1/4/tool1_4_t.jpg",
    "previewUrl":"https://www.leachchen.com/storetool1/4/tool1_4_p.gif",
    "downloadUrl":"https://www.cockos.com/licecap/",
    "description":"一款windows、mac系统录制gif动态图片的工具，免费简单方便使用",
    "type":"tool_synthesize1_1",
    "author":"licecap",
    "authorurl":"https://www.cockos.com/licecap/",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true
  },{
    "thumbUrl":"https://www.leachchen.com/storetool1/3/tool1_3_t.jpg",
    "previewUrl":"https://www.leachchen.com/storetool1/3/tool1_3_p.gif",
    "downloadUrl":"https://chrome.google.com/webstore/search/octotree?utm_source=chrome-ntp-icon",
    "description":"一款可以树形浏览Github代码的谷歌浏览器插件",
    "type":"tool_synthesize1_1",
    "author":"",
    "authorurl":"https://github.com/ovity/",
    "gitauthor":"ovity",
    "gitrepo":"octotree",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true
  },{
    "thumbUrl":"https://www.leachchen.com/storetool1/2/tool1_2_t.png",
    "previewUrl":"https://www.leachchen.com/storetool1/2/tool1_2_p.png",
    "downloadUrl":"https://netassist.updatestar.com/",
    "description":"网络调试助手，可通过路由器收发手机端广播包",
    "type":"tool_synthesize1_1",
    "author":"netassist",
    "authorurl":"https://netassist.updatestar.com/",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true
  },
		{
		"thumbUrl":"https://www.leachchen.com/storetool1/1/tool1_1_t.jpg",
		"previewUrl":"https://www.leachchen.com/storetool1/1/tool1_1_p.gif",
		"downloadUrl": "https://atom.io/",
		"description":"强大的ATOM编辑器，支持多种语言，插件丰富，推荐使用",
		"type":"tool_synthesize1_1",
		"author":"",
		"authorurl":"https://atom.io/",
		"gitauthor":"atom",
		"gitrepo":"atom",
		"byauthor":"",
		"byauthorurl":"",
		"sold":true
	}]
}
