{
	"dataToolSynthesize1":[{
    "thumbUrl":"https://www.leachchen.com/storetool1/2/tool1_2_t.png",
    "previewUrl":"https://netassist.updatestar.com/",
    "downloadUrl":"https://netassist.updatestar.com/",
    "description":"网络调试助手，可通过路由器收发手机端广播包",
    "type":"tool_synthesize1_1",
    "author":"netassist",
    "authorurl":"https://netassist.updatestar.com/",
    "gitauthor":"",
    "gitrepo":"",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true
  },
		{
		"thumbUrl":"https://www.leachchen.com/storetool1/1/tool1_1_t.jpg",
		"previewUrl":"https://www.leachchen.com/storetool1/1/tool1_1_p.gif",
		"downloadUrl": "https://atom.io/",
		"description":"强大的ATOM编辑器，支持多种语言，插件丰富，推荐使用",
		"type":"tool_synthesize1_1",
		"author":"",
		"authorurl":"https://atom.io/",
		"gitauthor":"atom",
		"gitrepo":"atom",
		"byauthor":"",
		"byauthorurl":"",
		"sold":true
	}]
}
