{
	"dataVueFull1":[{
    "thumbUrl":"https://www.leachchen.com/storevue1/2/vue1_2_t.jpg",
    "previewUrl":"https://im.aermin.top/login",
    "downloadUrl":"https://codeload.github.com/aermin/react-chat/zip/master",
    "description":"用react/vue全家桶+node.js(koa)+socket.io写的即时聊天应用",
    "type":"vue_full_1",
    "author":"",
    "authorurl":"",
    "gitauthor":"aermin",
    "gitrepo":"react-chat",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true
  },{
		"thumbUrl":"https://www.leachchen.com/storevue1/1/vue1_1_t.jpg",
		"previewUrl":"http://panjiachen.github.io/vue-element-admin",
		"downloadUrl":"https://codeload.github.com/PanJiaChen/vue-element-admin/zip/master",
		"description":"完整的Vue后台管理系统",
		"type":"vue_full_1",
		"author":"",
		"authorurl":"https://github.com/PanJiaChen/",
		"gitauthor":"PanJiaChen",
		"gitrepo":"vue-element-admin",
		"byauthor":"",
		"byauthorurl":"",
		"sold":true
	}]
}
