{
	"dataVueFull1":[{
    "thumbUrl":"https://www.leachchen.com/storevue1/3/vue1_3_t.png",
    "previewUrl":"https://d2admin.fairyever.com",
    "downloadUrl":"https://codeload.github.com/d2-projects/d2-admin/zip/master",
    "description":"优雅的中台系统前端模板",
    "type":"vue_full_1",
    "author":"FairyEver",
    "authorurl":"https://github.com/FairyEver",
    "gitauthor":"d2-projects",
    "gitrepo":"d2-admin",
    "byauthor":"FairyEver",
    "byauthorurl":"https://github.com/FairyEver",
    "sold":true
  },{
    "thumbUrl":"https://www.leachchen.com/storevue1/2/vue1_2_t.jpg",
    "previewUrl":"https://im.aermin.top/login",
    "downloadUrl":"https://codeload.github.com/aermin/react-chat/zip/master",
    "description":"用react/vue/node(koa)/socket写的即时聊天应用",
    "type":"vue_full_1",
    "author":"",
    "authorurl":"https://github.com/aermin",
    "gitauthor":"aermin",
    "gitrepo":"react-chat",
    "byauthor":"",
    "byauthorurl":"",
    "sold":true
  },{
		"thumbUrl":"https://www.leachchen.com/storevue1/1/vue1_1_t.jpg",
		"previewUrl":"http://panjiachen.github.io/vue-element-admin",
		"downloadUrl":"https://codeload.github.com/PanJiaChen/vue-element-admin/zip/master",
		"description":"完整的Vue后台管理系统",
		"type":"vue_full_1",
		"author":"",
		"authorurl":"https://github.com/PanJiaChen/",
		"gitauthor":"PanJiaChen",
		"gitrepo":"vue-element-admin",
		"byauthor":"",
		"byauthorurl":"",
		"sold":true
	}]
}
