{
	"dataWebsiteCss1":[{
		"id":"website_1",
		"time":"",
		"thumbUrl":"https://www.leachchen.com/storewebsite1/1/website1_1_t.png",
		"previewUrl":"https://www.leachchen.com/storewebsite1/1/website1_1_p_highway",
		"downloadUrl":"https://www.leachchen.com/storewebsite1/1/website1_1_d_highway.zip",
		"description":"旅游类型的纯CSS网站",
		"type":"website_css_1",
		"author":"模板之家",
		"authorurl":"http://www.cssmoban.com",
		"gitauthor":"",
		"gitrepo":"",
		"byauthor":"",
		"byauthorurl":"",
		"tag": "website",
		"sold":true
	}]
}
